import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingBottom: 28,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
  },
  headerSpacer: {
    width: 44,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#353744',
    fontSize: 17,
    fontWeight: '700',
  },
  subtitle: {
    textAlign: 'center',
    fontSize: 13,
    color: '#888394',
    marginBottom: 20,
  },
  businessCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    marginBottom: 20,
    shadowColor: '#8C6A9D',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 1,
  },
  businessIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#F4EDFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  businessInfo: {
    flex: 1,
  },
  businessName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#353744',
    marginBottom: 5,
  },
  address: {
    fontSize: 12,
    lineHeight: 18,
    color: '#7B8292',
  },
  reference: {
    fontSize: 11,
    lineHeight: 17,
    fontStyle: 'italic',
    color: '#9393A1',
    marginTop: 3,
  },
  mapCard: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    marginBottom: 20,
  },
  mapImage: {
    width: '100%',
    height: 200,
  },
  mapPlaceholder: {
    minHeight: 200,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    backgroundColor: '#F0EAF6',
  },
  locationIcon: {
    marginBottom: 10,
  },
  mapPlaceholderTitle: {
    color: '#65516F',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 6,
  },
  mapPlaceholderText: {
    color: '#8B7B96',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  directionsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 46,
    gap: 8,
    paddingVertical: 12,
  },
  directionsText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  contactRow: {
    flexWrap: 'wrap',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 22,
  },
  contactCard: {
    flex: 1,
    minWidth: 90,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 100,
    paddingHorizontal: 6,
    paddingVertical: 14,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    gap: 10,
    shadowColor: '#8C6A9D',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 7,
    elevation: 1,
  },
  contactIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#41414F',
  },
  disabled: { opacity: 0.6 },
  pending: { fontSize: 11, color: '#555360', textAlign: 'center' },
  pendingNotice: { fontSize: 12, color: '#7E798B', marginBottom: 16 },
  error: { fontSize: 13, color: '#B35478', marginBottom: 16 },
  pressed: {
    opacity: 0.7,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#353744',
    marginBottom: 12,
  },
  scheduleCard: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
  },
  statusRow: {
    alignItems: 'flex-end',
    marginBottom: 14,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#E5F8F0',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#20AC8A',
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#209C7E',
  },
  closedBadge: {
    backgroundColor: '#F7EAF0',
  },
  closedDot: {
    backgroundColor: '#C26086',
  },
  closedText: {
    color: '#B35478',
  },
  scheduleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
    paddingVertical: 10,
  },
  scheduleDivider: {
    borderTopWidth: 1,
    borderTopColor: '#F0EDF3',
  },
  scheduleDays: {
    fontSize: 12,
    fontWeight: '600',
    color: '#555360',
  },
  scheduleHours: {
    fontSize: 12,
    color: '#7E798B',
  },
  scheduleEmpty: {
    fontSize: 12,
    color: '#7E798B',
    lineHeight: 18,
  },
});
