import { StyleSheet } from 'react-native';
import { layout, palette, radius, spacing } from '@/shared/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  content: { width: '100%', maxWidth: layout.contentMaxWidth, alignSelf: 'center', paddingHorizontal: spacing.lg, paddingBottom: spacing.xl },
  title: { textAlign: 'center', fontSize: 20, fontWeight: '700', color: palette.text, paddingVertical: spacing.xl },
  search: { flexDirection: 'row', alignItems: 'center', minHeight: 46, gap: spacing.sm, paddingLeft: spacing.md, borderRadius: radius.pill, borderWidth: 1, borderColor: '#ECE8F0', backgroundColor: palette.surface },
  input: { flex: 1, minWidth: 0, paddingVertical: spacing.md, fontSize: 14, color: palette.text },
  iconButton: { minWidth: 44, minHeight: 44, justifyContent: 'center', alignItems: 'center' },
  categories: { gap: spacing.sm, paddingVertical: spacing.lg },
  chip: { borderRadius: radius.pill, backgroundColor: palette.surface, borderWidth: 1, borderColor: '#ECE8F0', minHeight: 44, paddingHorizontal: spacing.lg, justifyContent: 'center', alignItems: 'center' },
  activeChip: { backgroundColor: 'transparent', paddingHorizontal: 0, borderWidth: 0 },
  chipFill: { borderRadius: radius.pill, minHeight: 44, paddingHorizontal: spacing.lg, justifyContent: 'center' },
  chipText: { fontSize: 13, color: palette.textMuted },
  activeChipText: { color: palette.white, fontWeight: '600' },
  banner: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, alignItems: 'center', borderWidth: 1, borderColor: '#EBA9CC', borderRadius: radius.md, paddingHorizontal: spacing.md, marginBottom: spacing.md },
  bannerIcon: { width: 30, height: 30, backgroundColor: palette.surface, borderRadius: radius.pill, justifyContent: 'center', alignItems: 'center' },
  bannerText: { flex: 1, minWidth: 125, paddingVertical: spacing.md, fontSize: 12, fontWeight: '600', color: palette.text },
  link: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 2 },
  linkText: { fontSize: 11, color: palette.secondary, fontWeight: '600' },
  preview: { color: palette.textMuted, fontSize: 11, lineHeight: 16, marginBottom: spacing.md },
  row: { gap: spacing.md },
  separator: { height: spacing.md },
  card: { flex: 1, minWidth: 0, backgroundColor: palette.surface, borderRadius: radius.lg, padding: 10, gap: 6, shadowColor: '#957AA7', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.06, shadowRadius: 9, elevation: 2 },
  imageFrame: { width: '100%', aspectRatio: 1.15, maxHeight: 180, overflow: 'hidden', borderRadius: radius.sm, backgroundColor: '#F7F3EF' },
  image: { position: 'absolute', top: 0, left: 0, width: '100%', height: '100%' },
  imageFallback: { alignItems: 'center', justifyContent: 'center' },
  brandRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 4 },
  brand: { color: '#CC4A9B', fontSize: 11, fontWeight: '700' },
  status: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  statusDot: { width: 5, height: 5, borderRadius: radius.pill, backgroundColor: palette.success },
  soldOutDot: { backgroundColor: '#D87169' },
  unknownDot: { backgroundColor: palette.textSubtle },
  statusText: { fontSize: 10, color: palette.textMuted },
  name: { fontSize: 14, lineHeight: 19, fontWeight: '700', color: palette.text },
  presentation: { fontSize: 12, color: palette.textMuted },
  priceRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 3, marginTop: 'auto' },
  price: { fontSize: 15, color: palette.secondaryBright, fontWeight: '700' },
  pressed: { opacity: 0.7 },
  empty: { alignItems: 'center', gap: spacing.md, padding: spacing.xl },
  emptyText: { fontSize: 16, fontWeight: '700', color: palette.text, textAlign: 'center' },
  secondaryText: { fontSize: 13, color: palette.textMuted, textAlign: 'center', lineHeight: 20 },
});
