import { StyleSheet } from 'react-native';
import { layout, palette, radius, spacing } from '@/shared/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F9FAFC' },
  scroll: { flex: 1 },
  container: { width: '100%', maxWidth: layout.contentMaxWidth, alignSelf: 'center' },
  hero: { backgroundColor: '#F4F4F5' },
  toolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
  iconButton: { width: 44, height: 44, borderRadius: radius.pill, backgroundColor: palette.surface, justifyContent: 'center', alignItems: 'center', shadowColor: '#4B3859', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 1 },
  galleryImage: { height: 230, width: '100%', backgroundColor: '#F4F4F5' },
  imageFallback: { justifyContent: 'center', alignItems: 'center' },
  dots: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', minHeight: 44, backgroundColor: palette.surface },
  dotButton: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center' },
  dot: { width: 5, height: 5, borderRadius: radius.pill, backgroundColor: '#DBDEE7' },
  activeDot: { width: 16, backgroundColor: palette.primaryBright },
  body: { padding: spacing.lg, gap: spacing.md },
  brand: { fontSize: 11, fontWeight: '700', color: palette.secondaryBright },
  name: { fontSize: 24, lineHeight: 30, fontWeight: '700', color: palette.text },
  tags: { flexDirection: 'row', gap: spacing.sm, flexWrap: 'wrap' },
  category: { backgroundColor: palette.primaryBright, paddingHorizontal: spacing.md, paddingVertical: 4, borderRadius: radius.pill },
  categoryText: { color: palette.white, fontSize: 12, fontWeight: '600' },
  presentation: { paddingHorizontal: spacing.md, paddingVertical: 4, borderRadius: radius.pill, borderWidth: 1, borderColor: palette.border },
  presentationText: { color: palette.textMuted, fontSize: 12 },
  price: { fontSize: 28, fontWeight: '800', color: palette.primaryBright },
  stockRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, alignItems: 'center' },
  availability: { fontSize: 12, fontWeight: '600', color: '#168A6D' },
  soldOut: { color: '#BE5A64' },
  secondaryText: { fontSize: 13, lineHeight: 20, color: palette.textMuted },
  description: { backgroundColor: palette.surface, borderRadius: radius.lg, padding: spacing.lg, borderWidth: 1, borderColor: '#E6EAF0', gap: spacing.sm },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: palette.text },
  features: { gap: spacing.sm },
  featureRow: { flexDirection: 'row', gap: spacing.sm, alignItems: 'flex-start' },
  featureText: { flex: 1, color: palette.text, fontSize: 13, lineHeight: 20 },
  check: { backgroundColor: '#F0E9FF', borderRadius: radius.pill, padding: 3 },
  usage: { backgroundColor: '#FFF3F8', borderWidth: 1, borderColor: '#EAA6CA', borderRadius: radius.lg, padding: spacing.lg, gap: spacing.sm },
  usageTitle: { color: palette.primaryBright, fontSize: 15, fontWeight: '700' },
  quantitySection: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.md },
  quantity: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#EDF1F6', borderRadius: radius.pill, opacity: 0.6 },
  quantityButton: { width: 48, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  quantityText: { minWidth: 30, textAlign: 'center', color: palette.textMuted, fontSize: 16, fontWeight: '600' },
  restriction: { color: palette.textMuted, fontSize: 11, textAlign: 'center', lineHeight: 17 },
  preview: { color: palette.textMuted, fontSize: 11, lineHeight: 17 },
  error: { color: palette.error, fontSize: 13, lineHeight: 20 },
  footer: { backgroundColor: palette.surface, borderTopWidth: 1, borderColor: '#ECE8F0' },
  footerBody: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.md, padding: spacing.lg, maxWidth: layout.contentMaxWidth, width: '100%', alignSelf: 'center' },
  footerLabel: { fontSize: 10, color: palette.textMuted, fontWeight: '600' },
  footerPrice: { fontSize: 20, fontWeight: '800', color: palette.text },
  loginButton: { flex: 1, minWidth: 160, borderRadius: radius.pill, overflow: 'hidden' },
  loginFill: { minHeight: 48, paddingHorizontal: spacing.lg, paddingVertical: spacing.md, alignItems: 'center', justifyContent: 'center' },
  loginText: { color: palette.white, fontWeight: '700', fontSize: 13, textAlign: 'center' },
  pressed: { opacity: 0.7 },
  disabled: { opacity: 0.5 },
  missing: { flex: 1, padding: spacing.xl, justifyContent: 'center', alignItems: 'center', gap: spacing.lg },
});
