import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FBF7FF' },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 7,
  },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: { width: 30, height: 35 },
  logoFallback: {
    width: 30,
    height: 35,
    borderRadius: 12,
    backgroundColor: '#FCE7F3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoLetter: {
    color: '#8B42B5',
    fontWeight: '800',
    fontSize: 20,
  },
  brandName: {
    flex: 1,
    color: '#423448',
    fontSize: 16,
    fontFamily: 'serif',
  },
  profileButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },

  body: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingBottom: 24,
    gap: 14,
  },
  banner: {
    height: 190,
    borderRadius: 18,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  bannerCaption: { padding: 15, paddingTop: 45, gap: 5 },
  bannerTitle: {
    color: '#FFFFFF',
    fontFamily: 'serif',
    fontSize: 22,
    lineHeight: 28,
  },
  bannerSubtitle: {
    color: '#FFFFFF',
    fontSize: 11,
    lineHeight: 17,
  },
  dots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 5,
    marginTop: 10,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#D7CDDF',
  },
  activeDot: { backgroundColor: '#E843A0' },

  buttonRow: { flexDirection: 'row', gap: 12, marginTop: 2 },
  outlineButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#CD398B',
    backgroundColor: '#FFFFFF',
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  outlineText: {
    color: '#B32A7F',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  gradientButton: {
    flex: 1,
    borderRadius: 24,
    overflow: 'hidden',
  },
  buttonFill: {
    flex: 1,
    minHeight: 44,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },

  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 6,
  },
  sectionTitle: {
    flex: 1,
    fontFamily: 'serif',
    fontSize: 21,
    color: '#423448',
  },
  smallButton: {
    minHeight: 44,
    justifyContent: 'center',
  },
  link: { color: '#7D3BBB', fontSize: 12, fontWeight: '600' },

  promotionRow: { flexDirection: 'row', gap: 12 },
  promotionCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F0E9F5',
  },
  fullPromotion: { flex: 0, marginBottom: 16 },
  promotionImage: { width: '100%', height: 105 },
  promotionPlaceholder: {
    height: 105,
    backgroundColor: '#F2E5F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  promotionBody: { padding: 12, gap: 5 },
  promotionBadge: {
    color: '#AC287A',
    backgroundColor: '#FCE7F3',
    alignSelf: 'flex-start',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
    fontSize: 9,
    fontWeight: '700',
  },
  promotionTitle: {
    color: '#423448',
    fontSize: 13,
    fontWeight: '700',
  },
  validity: { color: '#73677B', fontSize: 10, lineHeight: 16 },

  servicesRow: { flexDirection: 'row', gap: 10 },
  serviceCard: {
    flex: 1,
    minHeight: 92,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F0E9F5',
    padding: 14,
    alignItems: 'center',
    gap: 10,
  },
  serviceIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#F6EFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  serviceName: {
    color: '#423448',
    fontSize: 12,
    fontWeight: '600',
  },

  overlay: {
    flex: 1,
    backgroundColor: 'rgba(30,15,40,0.45)',
  },
  sidebar: {
    height: '100%',
    backgroundColor: '#FFFFFF',
  },
  sidebarBody: { padding: 18 },
  sidebarHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sidebarTitle: {
    color: '#423448',
    fontSize: 20,
    fontWeight: '700',
  },
  sidebarBrand: {
    color: '#873EB5',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 20,
  },
  sidebarSubtitle: {
    color: '#73677B',
    fontSize: 12,
    marginTop: 5,
    marginBottom: 25,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 58,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F2EAF6',
  },
  menuText: { flex: 1, color: '#423448', fontSize: 14 },
  sidebarLogin: {
    backgroundColor: '#8B42D7',
    borderRadius: 24,
    minHeight: 46,
    padding: 14,
    marginTop: 28,
    justifyContent: 'center',
  },

  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
  },
  detailTitle: {
    flex: 1,
    color: '#423448',
    fontSize: 19,
    fontWeight: '700',
  },
  detailBody: { padding: 22, paddingBottom: 40 },
  contentTitle: {
    color: '#663086',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 18,
    marginBottom: 10,
  },
  paragraph: {
    color: '#63516B',
    fontSize: 14,
    lineHeight: 24,
  },
  empty: { alignItems: 'center', paddingVertical: 40, gap: 12 },
});
