import { StyleSheet } from 'react-native';
import { layout, palette, radius, spacing } from '@/shared/theme/tokens';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  content: { width: '100%', maxWidth: layout.contentMaxWidth, alignSelf: 'center', paddingHorizontal: spacing.lg, paddingBottom: spacing.xl },
  title: { textAlign: 'center', color: palette.text, fontWeight: '700', fontSize: 20, paddingTop: spacing.lg, paddingBottom: spacing.xl },
  search: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingLeft: spacing.md, borderRadius: radius.pill, backgroundColor: palette.surface, borderWidth: 1, borderColor: '#ECE8F0', minHeight: 46 },
  input: { flex: 1, minWidth: 0, fontSize: 14, color: palette.text, paddingVertical: spacing.md },
  iconButton: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  categories: { gap: spacing.sm, paddingVertical: spacing.lg },
  chip: { minHeight: 44, paddingHorizontal: spacing.lg, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.surface, borderWidth: 1, borderColor: '#ECE8F0', borderRadius: radius.pill },
  selectedChip: { borderWidth: 0, paddingHorizontal: 0, backgroundColor: 'transparent' },
  chipGradient: { minHeight: 44, paddingHorizontal: spacing.lg, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill },
  chipText: { color: palette.textMuted, fontSize: 13 },
  selectedChipText: { color: palette.white, fontWeight: '600' },
  filterRow: { alignItems: 'flex-end', marginBottom: spacing.lg },
  filterButton: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center', minHeight: 44, borderRadius: radius.pill, paddingHorizontal: spacing.md, backgroundColor: palette.surface, borderWidth: 1, borderColor: '#ECE8F0' },
  filterText: { color: palette.text, fontSize: 13, fontWeight: '600' },
  badge: { borderRadius: radius.pill, minWidth: 20, height: 20, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 5 },
  badgeText: { color: palette.white, fontSize: 11, fontWeight: '700' },
  loginBanner: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.sm, borderWidth: 1, borderColor: '#EBA9CC', borderRadius: radius.md, paddingHorizontal: spacing.md, marginBottom: spacing.lg },
  loginIcon: { width: 30, height: 30, borderRadius: radius.pill, backgroundColor: palette.surface, alignItems: 'center', justifyContent: 'center' },
  loginText: { flex: 1, minWidth: 130, paddingVertical: spacing.md, color: palette.text, fontSize: 12, lineHeight: 18, fontWeight: '600' },
  linkButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 2 },
  linkText: { color: palette.secondary, fontSize: 12, fontWeight: '600' },
  preview: { fontSize: 11, lineHeight: 16, color: palette.textMuted, marginBottom: spacing.md },
  card: { flexDirection: 'row', alignItems: 'center', padding: spacing.md, gap: spacing.md, borderRadius: radius.lg, backgroundColor: palette.surface, shadowColor: '#957AA7', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.07, shadowRadius: 10, elevation: 2 },
  image: { width: 90, height: 100, borderRadius: radius.sm, backgroundColor: '#F5EDF8' },
  imageCompact: { width: 68, height: 86 },
  imageFallback: { alignItems: 'center', justifyContent: 'center' },
  cardBody: { flex: 1, minWidth: 0, gap: 5 },
  categoryLabel: { alignSelf: 'flex-start', backgroundColor: '#FFF0F7', borderRadius: 4, paddingHorizontal: 5, paddingVertical: 2 },
  categoryText: { fontSize: 10, color: '#BB357D', fontWeight: '600' },
  serviceName: { fontSize: 14, color: palette.text, fontWeight: '700', lineHeight: 20 },
  metadata: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', justifyContent: 'space-between', gap: 6 },
  price: { fontSize: 14, fontWeight: '700', color: palette.secondaryBright },
  duration: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  durationText: { fontSize: 11, color: palette.textMuted },
  separator: { height: spacing.md },
  pressed: { opacity: 0.7 },
  empty: { alignItems: 'center', padding: spacing.xl, gap: spacing.md },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: palette.text, textAlign: 'center' },
  secondaryText: { color: palette.textMuted, fontSize: 14, lineHeight: 21 },
  centered: { textAlign: 'center' },
  overlay: { flex: 1, backgroundColor: '#271A3E66', justifyContent: 'flex-end' },
  dismissArea: { flex: 1 },
  sheet: { maxHeight: '85%', width: '100%', maxWidth: layout.contentMaxWidth, alignSelf: 'center', backgroundColor: palette.background, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl },
  sheetContent: { padding: spacing.xl, gap: spacing.lg },
  sheetHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm },
  sheetTitle: { flex: 1, fontSize: 20, fontWeight: '700', color: palette.text },
  filterOption: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, minHeight: 56 },
  optionText: { flex: 1, color: palette.text, fontSize: 15 },
  primaryButton: { borderRadius: radius.md, overflow: 'hidden' },
  primaryFill: { minHeight: 48, alignItems: 'center', justifyContent: 'center', padding: spacing.md },
  primaryText: { color: palette.white, fontSize: 15, fontWeight: '700', textAlign: 'center' },
  detailImage: { width: '100%', height: 200, borderRadius: radius.lg },
});
